### ISSUE TITLE
Can input be anything other than URL 

### ISSUE THREAD

**Issue by hackable** [bbondy/abp-filter-parser#12]
Can i use  class or id of div or file name instead of URL.

let urlToCheck = 'http://example.net/anyad.js';

returns  true;

to 

let urlToCheck = 'anyad.js';

returns false

**Comment by bbondy** [comment]
it should always be a full url

**Comment by hackable** [comment]
But Easylist has classes and div names are they not supported such as

###wideAdd
###wide_ad_unit
###wide_ad_unit2
###wide_ad_unit_2
###wide_ad_unit_top

**Comment by bbondy** [comment]
cosmetic filters will work differently, it will generate a stylesheet that should be applied with a bunch of CSS selectors and a body of `display: none`
