### ISSUE TITLE
Is it possible to use this in the browser?

### ISSUE THREAD

**Issue by r1b** [bbondy/abp-filter-parser#14]
Let's say I wanted to use the parser in a chrome extension. How can I accomplish this?

**Comment by r1b** [comment]
I poked around to try and get a webpack build working - realized there is a dependency on `fs`:

``` javascript
fs.writeFileSync('easylist-matches.json', JSON.stringify(cachedInputData.matchedFilters), 'utf-8');
```

Is this just for debugging?

**Comment by r1b** [comment]
Further poking leads me to believe the answer is "no, not possible" - but if you have any thoughts on how to make this possible I would be interested :)

**Comment by bbondy** [comment]
your best bet is probably to run this through emscripten, 
https://github.com/bbondy/abp-filter-parser-cpp

Would love a pull request for a build script for that if you end up doing it.
